# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
variables:
   MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress


# run with docker, choose maven 3.9.0 with latest Java and a small linux footprint
image: maven:3.9.6-eclipse-temurin-21-alpine

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
   - .m2/repository

stages:
  - build
  - site

build-job:
  # Your specification comes here
  stage: build
  script:
    - mvn install:install-file -Dfile=./lib/pi4jlib-1.0.jar -DgroupId=com.pi4j -DartifactId=pi4jlib -Dversion=1.0.0 -Dpackaging=jar
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    when: always


pages:
  stage: site
  script:
    - mvn install:install-file -Dfile=./lib/pi4jlib-1.0.jar -DgroupId=com.pi4j -DartifactId=pi4jlib -Dversion=1.0.0 -Dpackaging=jar
    - mvn validate
    - mvn site
    - mv target/site public
  rules:
  - when: always
  artifacts:
    paths:
    - public
