= Coding Conventions

== Verwendete Konventionen

Folgende Konventionen werden im Projekt EnergieClassh eingehalten:

* Namenskonventionen: Packagenamen sind immer klein,
* Klassen sind CamelCase, Variablen sind drinkingCamelCase, Konstanten und Enums sind in UPPER_CASE.
* 1 Tabulator/4 Leerschläge Einrückung pro Block.
* Keine Mehrfachdeklarationen pro Zeile.
* Öffnende Klammer auf der vorherigen Zeile, schliessende auf eine neue Zeile.
* Zeilen sind max. 120 Zeichen lang
* Verkettungen sind umgebrochen auf neue Zeilen mit 8 Leerzeichen Einrückung
* Klassengrösse: nicht grösser als 300 Zeilen
* ...

Im Projekt EnergieClash wird eine link:https://checkstyle.sourceforge.io/[Checkstyle] Konfiguration verwendet.
Weitere Details zu den Coding Conventions finden Sie in der
link:https://github.com/fhnw-sgi-ip12-23vt/ip12-23vt_energie-clash/blob/main/Code/src/main/resources/checkstyle/energieclash-java-formatter.xml[energieclash-java-formatter] Konfigurationsdatei.

== Sicherstellung der Einhaltung der Konventionen

Das Projekt wird mit dem link:https://maven.apache.org/[Maven] Build Automation Tool verwaltet. In der Maven "build"-Phase werden alle Java Dateien vom Maven Checkstyle plugin überprüft. Danach wird vom link:https://maven.apache.org/plugins/maven-site-plugin/["site"-Plugin] ein Report erstellt, welcher alle Verletzungen der Coding Conventions beinhaltet.

Mit der link:https://docs.gitlab.com/ee/ci/pipelines/[Gitlab CI/CD Pipeline] kann bei jedem commit auf das Repository ein build durchgeführt und das Reporting erstellt werden.
Das heisst, nach jedem commit liegt ein Report vor welcher dann auf einer generierten Gitlab Page als HTML-Seite verfügbar ist.

Das Konfigurationsfile der Pipeline finden Sie xref:https://github.com/fhnw-sgi-ip12-23vt/ip12-23vt_energie-clash/blob/main/Code/.gitlab-ci.yml[hier].
